// lib/blogData.ts
export const blogPosts = [
    {
        slug: 'artificial-intelligence',
        title: 'Artificial Intelligence',
        content: 'Learn how to create an office environment that boosts productivity and employee satisfaction...',
        image: '/ai.jpg?height=400&width=800',
        author: 'Ali Asghar',
        date: '2023-06-01',
        category: 'tech',
    },
    {
        slug: '5g-internet',
        title: '5G Internet',
        content: 'Explore the latest web development trends to stay ahead in the tech industry...',
        image: '/5g.jpg?height=400&width=800',
        author: 'Ali Asghar',
        date: '2024-12-15',
        category: 'internet',
    },
    {
        slug: 'quantum-computing',
        title: 'Quantum Computing',
        content: 'Explore the latest web development trends to stay ahead in the tech industry...',
        image: '/qc.jpg?height=400&width=800',
        author: 'Ali Asghar',
        date: '2024-12-15',
        category: 'Quantum Computing',
    },
     {
        slug: 'metaverse',
        title: 'Metaverse',
        content: 'Explore the latest web development trends to stay ahead in the tech industry...',
        image: '/meta.jpg?height=400&width=800',
        author: 'Ali Asghar',
        date: '2024-12-15',
        category: 'Metaverse',
    },
     {
        slug: 'blockchain',
        title: 'Blockchain',
        content: 'Explore the latest web development trends to stay ahead in the tech industry...',
        image: '/block.jpg?height=400&width=800',
        author: 'Ali Asghar',
        date: '2024-12-15',
        category: 'Fiance',
    },
    {
        slug: 'cybersecurity',
        title: 'Cybersecurity',
        content: 'Explore the latest web development trends to stay ahead in the tech industry...',
        image: '/auto.jpg?height=400&width=800',
        author: 'Ali Asghar',
        date: '2024-12-15',
        category: 'Cybersecurity',
    },
    // Add more blog posts as needed
]
